apiVersion: apps/v1
kind: Deployment
metadata:
  name: ExceptionHandlingDemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ExceptionHandlingDemo
  template:
    metadata:
      labels:
        app: ExceptionHandlingDemo
    spec:
      containers:
      - name: your-app-container
        image: <your-registry>.azurecr.io/yourdockerimage:latest
        ports:
        - containerPort: 80
